step by step

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -26,32 +26,32 @@ jobs:
         with:
           action: action.yml
 
-      - name: Setup Node 14.x
-        uses: MM12300/portfolio-CICD@main
-        with:
-          action: setup-node.yml
-          node-version: 14.x
-          cache: npm
-
-      - name: Install dependencies
-        run: npm ci
-
-      - name: Rebuild the dist/ directory
-        run: npm run build
-
-      - name: Compare the expected and actual dist/ directories
-        run: |
-          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
-            echo "Detected uncommitted changes after build.  See status below:"
-            git diff
-            exit 1
-          fi
-        id: diff
-
-      # If index.js was different than expected, upload the expected version as an artifact
-      - uses: MM12300/portfolio-CICD@main
-        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
-        with:
-          action : upload-artifact.yml
-          name: dist
-          path: dist/
+#      - name: Setup Node 14.x
+#        uses: MM12300/portfolio-CICD@main
+#        with:
+#          action: setup-node.yml
+#          node-version: 14.x
+#          cache: npm
+#
+#      - name: Install dependencies
+#        run: npm ci
+#
+#      - name: Rebuild the dist/ directory
+#        run: npm run build
+#
+#      - name: Compare the expected and actual dist/ directories
+#        run: |
+#          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
+#            echo "Detected uncommitted changes after build.  See status below:"
+#            git diff
+#            exit 1
+#          fi
+#        id: diff
+#
+#      # If index.js was different than expected, upload the expected version as an artifact
+#      - uses: MM12300/portfolio-CICD@main
+#        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
+#        with:
+#          action : upload-artifact.yml
+#          name: dist
+#          path: dist/
